defaults:
  - values:
      layout: default
exclude: [ Gemfile*, README*, bower*, vendor ]
permalink: /:categories/:year/:title.html
repo: ScotLUG/scotlug.github.io
sass:
  sass_dir: bower_components
title: Scottish Linux User Group
url: http://scotlug.github.io
future: true
